import React, { useState } from 'react';
import { ChevronDown, ChevronUp, Terminal, Clipboard, Check } from 'lucide-react';

export default function ChatMessage({ message }) {
  const { sender, text, sql } = message;
  const [sqlExpanded, setSqlExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  // Formats Markdown syntax generated by the LLM
  const renderMarkdown = (rawText) => {
    if (!rawText) return '';
    const lines = rawText.split('\n');
    let inList = false;
    const html = [];

    for (let line of lines) {
      line = line.trim();
      if (line.startsWith('###')) {
        if (inList) {
          html.push('</ul>');
          inList = false;
        }
        html.push(`<h3 style="font-size: 1rem; color: #60a5fa; margin: 16px 0 8px 0; border-bottom: 1px solid rgba(255,255,255,0.05); padding-bottom: 4px;">${line.slice(3).trim()}</h3>`);
      } else if (line.startsWith('-') || line.startsWith('*')) {
        if (!inList) {
          html.push('<ul style="padding-left: 20px; margin-bottom: 12px; list-style-type: disc;">');
          inList = true;
        }
        let formattedItem = line.slice(1).trim().replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
        formattedItem = formattedItem.replace(/`(.*?)`/g, '<code style="background: rgba(0,0,0,0.3); padding: 2px 4px; border-radius: 4px; font-family: monospace; font-size: 0.85rem; color: #f472b6;">$1</code>');
        html.push(`<li style="font-size: 0.9rem; margin-bottom: 6px; line-height: 1.5; color: #d1d5db;">${formattedItem}</li>`);
      } else if (line) {
        if (inList) {
          html.push('</ul>');
          inList = false;
        }
        let formattedLine = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
        formattedLine = formattedLine.replace(/`(.*?)`/g, '<code style="background: rgba(0,0,0,0.3); padding: 2px 4px; border-radius: 4px; font-family: monospace; font-size: 0.85rem; color: #f472b6;">$1</code>');
        html.push(`<p style="font-size: 0.9rem; line-height: 1.6; margin-bottom: 10px; color: #e5e7eb;">${formattedLine}</p>`);
      } else {
        if (inList) {
          html.push('</ul>');
          inList = false;
        }
      }
    }
    if (inList) {
      html.push('</ul>');
    }
    return html.join('');
  };

  const copySQL = () => {
    navigator.clipboard.writeText(sql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (sender === 'user') {
    return (
      <div className="message-bubble user">
        <span className="message-sender" style={{ color: 'rgba(255,255,255,0.7)' }}>You</span>
        <div className="message-content">
          <p style={{ margin: 0, fontSize: '0.95rem' }}>{text}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="message-bubble assistant">
      <span className="message-sender" style={{ color: '#60a5fa' }}>Procurement Analyst</span>
      <div 
        className="message-content" 
        dangerouslySetInnerHTML={{ __html: renderMarkdown(text) }} 
      />
      
      {sql && (
        <div className="sql-expander">
          <div 
            className="sql-header" 
            onClick={() => setSqlExpanded(!sqlExpanded)}
          >
            <span style={{ display: 'flex', alignItems: 'center', gap: '6px', fontWeight: 600 }}>
              <Terminal size={14} style={{ color: '#10b981' }} />
              SQLite Query Synthesized
            </span>
            <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
              {sqlExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
            </span>
          </div>
          {sqlExpanded && (
            <div style={{ position: 'relative' }}>
              <button 
                onClick={copySQL}
                style={{
                  position: 'absolute',
                  top: '8px',
                  right: '8px',
                  background: 'rgba(255,255,255,0.05)',
                  border: '1px solid rgba(255,255,255,0.1)',
                  borderRadius: '4px',
                  color: 'white',
                  cursor: 'pointer',
                  padding: '4px 6px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px',
                  fontSize: '0.7rem'
                }}
              >
                {copied ? <Check size={10} style={{ color: '#10b981' }} /> : <Clipboard size={10} />}
                {copied ? 'Copied' : 'Copy'}
              </button>
              <pre className="sql-body" style={{ margin: 0 }}>{sql}</pre>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
